In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [2]:
def get_textfile(dir, path, files):
    path = path + '/wiki_'
    for i in range(1):
        for j in range(0, 1):
            text_file = path + (str(i) + str(j)) + '.txt'
            files.append(text_file)



#dir = ['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI']
dir = ['AA']
base = '/content/drive/MyDrive/Colab Notebooks/text/'

files = []
for i in dir:
    path = base + i
    get_textfile(i, path,files)

text = ""
for file in files:
    sample = open(file,"r")
    s = sample.read()
    text += s

In [43]:
text

'지미 카터\n제임스 얼 카터 주니어는 민주당 출신 미국 39대 대통령 이다\n생애\n어린 시절\n지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다\n조지아 공과대학교를 졸업하였다\n그 후 해군에 들어가 전함원자력잠수함의 승무원으로 일하였다\n1953년 미국 해군 대위로 예편하였고 이후 땅콩면화 등을 가꿔 많은 돈을 벌었다\n그의 별명이 땅콩 농부 로 알려졌다\n정계 입문\n1962년 조지아주 상원 의원 선거에서 낙선하나 그 선거가 부정선거 였음을 입증하게 되어 당선되고 1966년 조지아 주지사 선거에 낙선하지만 1970년 조지아 주지사를 역임했다\n대통령이 되기 전 조지아주 상원의원을 두번 연임했으며 1971년부터 1975년까지 조지아 지사로 근무했다\n조지아 주지사로 지내면서 미국에 사는 흑인 등용법을 내세웠다\n대통령 재임\n1976년 미합중국 제39대 대통령 선거에 민주당 후보로 출마하여 도덕주의 정책으로 내세워서 많은 지지를 받고 제럴드 포드 대통령을 누르고 당선되었다\n카터 대통령은 에너지 개발을 촉구했으나 공화당의 반대로 무산되었다\n외교 정책\n카터는 이집트와 이스라엘을 조정하여 캠프 데이비드에서 안와르 사다트 대통령과 메나헴 베긴 수상과 함께 중동 평화를 위한 캠프데이비드 협정을 체결했다\n이것은 공화당과 미국의 유대인 단체의 반발을 일으켰다\n그러나 1979년 양국 간의 평화조약이 백악관에서 이루어졌다\n소련과 제2차 전략 무기 제한 협상에 조인했다\n카터는 1970년대 후반 당시 대한민국 등 인권 후진국의 국민들의 인권을 지키기 위해 노력했으며 취임 이후 계속해서 도덕정치를 내세웠다\n임기 말 소련의 아프가니스탄 침공 사건으로 인해 1980년 하계 올림픽에 반공국가들의 보이콧을 하였다\n그는 주이란 미국 대사관 인질 사건의 인질 구출 실패로 인한 원인으로 1980년 제40대 대통령 선거에서 공화당의 로널드 레이건에게 패하며 재선에 실패하였다\n대한민국과의 관계지미 카터는 대한민국과의 관계에서도 중요한 영향을 미쳤던 대통령 중 하나

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [44]:
# text = """경마장에 있는 말이 뛰고 있다\n
# 그의 말이 법이다\n
# 가는 말이 고와야 오는 말이 곱다\n"""

In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 21053


In [5]:
print(tokenizer.word_index)


{'있다': 1, '수': 2, '이': 3, '그': 4, '이후': 5, '대한': 6, '또한': 7, '있는': 8, '대한민국': 9, '등': 10, '한다': 11, '빼기': 12, '다음과': 13, '따라': 14, '같은': 15, '대한민국의': 16, '및': 17, '그러나': 18, '등의': 19, '같이': 20, '가장': 21, '때': 22, '있으며': 23, '많은': 24, '중': 25, '한': 26, '때문에': 27, '다른': 28, '통해': 29, '의해': 30, '두': 31, '등이': 32, '이러한': 33, '약': 34, '되었다': 35, '여러': 36, '위해': 37, '것으로': 38, '등을': 39, '함께': 40, '나누기': 41, '후': 42, '된다': 43, '한국': 44, '특히': 45, '했다': 46, '또는': 47, '노무현': 48, '이를': 49, '현재': 50, '있었다': 51, '이는': 52, '큰': 53, '모든': 54, '것을': 55, '서울': 56, '대통령': 57, '대해': 58, '하는': 59, '경우': 60, '들어': 61, '매우': 62, '것은': 63, '명': 64, '그는': 65, '더': 66, '선형': 67, '그리고': 68, '대한민국은': 69, '그의': 70, '하였다': 71, '이에': 72, '하지만': 73, '같다': 74, '일본': 75, '당시': 76, '즉': 77, '다시': 78, '한편': 79, '중국': 80, '것이': 81, '것이다': 82, '따라서': 83, '인구': 84, '인구는': 85, '위한': 86, '켓': 87, '미국': 88, '영향을': 89, '등으로': 90, '예를': 91, '일부': 92, '세계': 93, '주로': 94, '정부는': 95, '전': 96, '12월': 97, '서울의': 98, '미분': 99, '의': 

In [6]:
sequences = list()
for line in text.split('\n'): # 줄바꿈 문자를 기준으로 문장 토큰화
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 39805


In [7]:
print(sequences)


Output hidden; open in https://colab.research.google.com to view.

In [8]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 72


In [9]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')


In [10]:
print(sequences)


[[    0     0     0 ...     0  2963   996]
 [    0     0     0 ...     0  1869  5680]
 [    0     0     0 ...  1869  5680   996]
 ...
 [    0     0     0 ...  2026 21052  2962]
 [    0     0     0 ... 21052  2962  5679]
 [    0     0     0 ...  2962  5679    41]]


In [11]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [12]:
print(X)


[[    0     0     0 ...     0     0  2963]
 [    0     0     0 ...     0     0  1869]
 [    0     0     0 ...     0  1869  5680]
 ...
 [    0     0     0 ...  5678  2026 21052]
 [    0     0     0 ...  2026 21052  2962]
 [    0     0     0 ... 21052  2962  5679]]


In [13]:
print(y)


[ 996 5680  996 ... 2962 5679   41]


In [14]:
y = to_categorical(y, num_classes=vocab_size)


In [15]:
print(y)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

import tensorflow as tf

# GPU를 사용 가능한 경우, GPU를 사용하여 TensorFlow 코드를 실행합니다.
if tf.test.is_gpu_available():
    print("GPU 사용 가능")
    # GPU 메모리 할당 방식을 설정합니다.
    gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.5)
    sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(gpu_options=gpu_options))
else:
    print("GPU 사용 불가능")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


GPU 사용 가능


In [36]:
embedding_dim = 100
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=2)

Epoch 1/10
1244/1244 - 86s - loss: 9.8095 - accuracy: 0.0131 - 86s/epoch - 69ms/step
Epoch 2/10
1244/1244 - 57s - loss: 9.0647 - accuracy: 0.0139 - 57s/epoch - 46ms/step
Epoch 3/10
1244/1244 - 56s - loss: 8.4581 - accuracy: 0.0193 - 56s/epoch - 45ms/step
Epoch 4/10
1244/1244 - 56s - loss: 7.9328 - accuracy: 0.0305 - 56s/epoch - 45ms/step
Epoch 5/10
1244/1244 - 55s - loss: 7.4072 - accuracy: 0.0497 - 55s/epoch - 44ms/step
Epoch 6/10
1244/1244 - 54s - loss: 6.8915 - accuracy: 0.0750 - 54s/epoch - 43ms/step
Epoch 7/10
1244/1244 - 55s - loss: 6.3957 - accuracy: 0.1085 - 55s/epoch - 44ms/step
Epoch 8/10
1244/1244 - 54s - loss: 5.9280 - accuracy: 0.1493 - 54s/epoch - 44ms/step
Epoch 9/10
1244/1244 - 54s - loss: 5.4933 - accuracy: 0.1983 - 54s/epoch - 43ms/step
Epoch 10/10
1244/1244 - 54s - loss: 5.0915 - accuracy: 0.2479 - 54s/epoch - 44ms/step


In [47]:
model.fit(X, y, epochs=50, verbose=2)

Epoch 1/50
1244/1244 - 54s - loss: 0.4160 - accuracy: 0.9209 - 54s/epoch - 43ms/step
Epoch 2/50
1244/1244 - 54s - loss: 0.4040 - accuracy: 0.9225 - 54s/epoch - 43ms/step
Epoch 3/50
1244/1244 - 54s - loss: 0.3972 - accuracy: 0.9239 - 54s/epoch - 44ms/step
Epoch 4/50
1244/1244 - 54s - loss: 0.4036 - accuracy: 0.9223 - 54s/epoch - 43ms/step
Epoch 5/50
1244/1244 - 54s - loss: 0.4191 - accuracy: 0.9189 - 54s/epoch - 43ms/step
Epoch 6/50
1244/1244 - 53s - loss: 0.3852 - accuracy: 0.9247 - 53s/epoch - 43ms/step
Epoch 7/50
1244/1244 - 54s - loss: 0.3705 - accuracy: 0.9253 - 54s/epoch - 43ms/step
Epoch 8/50
1244/1244 - 54s - loss: 0.3647 - accuracy: 0.9277 - 54s/epoch - 43ms/step
Epoch 9/50
1244/1244 - 53s - loss: 0.3600 - accuracy: 0.9277 - 53s/epoch - 43ms/step
Epoch 10/50
1244/1244 - 53s - loss: 0.3612 - accuracy: 0.9272 - 53s/epoch - 43ms/step
Epoch 11/50
1244/1244 - 54s - loss: 0.3493 - accuracy: 0.9293 - 54s/epoch - 43ms/step
Epoch 12/50
1244/1244 - 54s - loss: 0.3448 - accuracy: 0.9289 -

In [21]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' '  + word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence

In [46]:
print(sentence_generation(model, tokenizer, '에너지', 2))


에너지 대한민국의 중화인민공화국과는


In [31]:
def s_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence

In [41]:
print(s_generation(model, tokenizer, '소련', 4))


소련 말해서 대한민국의 대한민국의 대한민국의
